version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306" #端口根据实际情况修改
    volumes:
      - ./db_data:/var/lib/mysql
      - /root/logs/mysql:/logs #log存放路径根据实际情况修改
      - /etc/localtime:/etc/localtime:ro
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: DATABASE_NAME
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_USER_PASSWORD
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "80:80" #端口根据实际情况修改
    volumes:
      - ./wp_site:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306 #数据库容器内部端口，非宿主机端口，一般不变
      WORDPRESS_DB_USER: MYSQL_USER #对应数据库相关参数
      WORDPRESS_DB_PASSWORD: MYSQL_PASSWORD #对应数据库相关参数
      WORDPRESS_DB_NAME: MYSQL_DATABASE #对应数据库相关参数
volumes:
  db_data:
  wp_site: